//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chat
    {
        public Chat()
        {
            this.ChatSubscribers = new HashSet<ChatSubscriber>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdChatTopic { get; set; }
        public Nullable<int> Grade { get; set; }
        public Nullable<int> IdChatCategory { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual ChatCategory ChatCategory { get; set; }
        public virtual ChatTopic ChatTopic { get; set; }
        public virtual ICollection<ChatSubscriber> ChatSubscribers { get; set; }
    }
}
