//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int Id { get; set; }
        public Nullable<int> IdCourse { get; set; }
        public Nullable<int> IdUser { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> IdEventType { get; set; }
        public string Syllabus { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual EventType EventType { get; set; }
        public virtual User User { get; set; }
    }
}
