//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoticeType
    {
        public NoticeType()
        {
            this.SetNotices = new HashSet<SetNotice>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> IdDeliveryFrequency { get; set; }
    
        public virtual DeliveryFrequency DeliveryFrequency { get; set; }
        public virtual ICollection<SetNotice> SetNotices { get; set; }
    }
}
