//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageDesign
    {
        public int Id { get; set; }
        public Nullable<int> TextSize { get; set; }
        public string TextStyle { get; set; }
        public string TextColor { get; set; }
        public string BackgroundColor { get; set; }
        public string Alignment { get; set; }
        public int IdUser { get; set; }
    
        public virtual User User { get; set; }
    }
}
