//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.QuizQuestions = new HashSet<QuizQuestion>();
        }
    
        public int Id { get; set; }
        public string Content { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<int> IdGroup { get; set; }
        public string Description { get; set; }
        public string CorrectAnswer { get; set; }
        public Nullable<int> IdQuestionType { get; set; }
    
        public virtual GroupHomeworkQuestion GroupHomeworkQuestion { get; set; }
        public virtual QuestionType QuestionType { get; set; }
        public virtual ICollection<QuizQuestion> QuizQuestions { get; set; }
    }
}
