//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quiz
    {
        public Quiz()
        {
            this.QuizQuestions = new HashSet<QuizQuestion>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public Nullable<int> IdQuizType { get; set; }
        public Nullable<int> IdStudentGroup { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> CompletionDeadline { get; set; }
        public Nullable<int> MaximumNumberOfAttempts { get; set; }
        public Nullable<int> IdKeepScoreType { get; set; }
        public Nullable<int> DisplayPersonalAnswer { get; set; }
        public string Password { get; set; }
        public string IPAdress { get; set; }
    
        public virtual KeepScoreType KeepScoreType { get; set; }
        public virtual QuizType QuizType { get; set; }
        public virtual StudentsGroup StudentsGroup { get; set; }
        public virtual ICollection<QuizQuestion> QuizQuestions { get; set; }
    }
}
