//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizQuestion
    {
        public int Id { get; set; }
        public Nullable<int> IdQuestion { get; set; }
        public Nullable<int> IdQuiz { get; set; }
        public Nullable<int> IdCourse { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Question Question { get; set; }
        public virtual Quiz Quiz { get; set; }
    }
}
