//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource
    {
        public Resource()
        {
            this.Homework = new HashSet<Homework>();
            this.ResourcePosts = new HashSet<ResourcePost>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int IdCategory { get; set; }
    
        public virtual ICollection<Homework> Homework { get; set; }
        public virtual ResourceCategory ResourceCategory { get; set; }
        public virtual ICollection<ResourcePost> ResourcePosts { get; set; }
    }
}
