//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetNotice
    {
        public int Id { get; set; }
        public Nullable<int> IdUser { get; set; }
        public Nullable<int> IdNoticeType { get; set; }
        public Nullable<int> IdFrequency { get; set; }
    
        public virtual DeliveryFrequency DeliveryFrequency { get; set; }
        public virtual NoticeType NoticeType { get; set; }
        public virtual User User { get; set; }
    }
}
