//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TurninType
    {
        public TurninType()
        {
            this.Homework = new HashSet<Homework>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Name { get; set; }
    
        public virtual ICollection<Homework> Homework { get; set; }
    }
}
